import type { ScriptureVolumeId } from "./sanctuaryScripture";

/**
 * Verse of the day, drawn across all four standard works. Verse text only, from
 * the public-domain editions in `public/sanctuary/scriptures`, so the home view
 * never has to load a whole volume.
 */
export const DAILY_VERSES: ReadonlyArray<
  readonly [volume: ScriptureVolumeId, book: string, chapter: number, verse: number, text: string]
> = [
  [
    "book-of-mormon",
    "1 Nephi",
    3,
    7,
    "And it came to pass that I, Nephi, said unto my father: I will go and do the things which the Lord hath commanded, for I know that the Lord giveth no commandments unto the children of men, save he shall prepare a way for them that they may accomplish the thing which he commandeth them.",
  ],
  [
    "old-testament",
    "Joshua",
    1,
    9,
    "Have not I commanded thee? Be strong and of a good courage; be not afraid, neither be thou dismayed: for the LORD thy God is with thee whithersoever thou goest.",
  ],
  [
    "doctrine-and-covenants",
    "D&C",
    1,
    38,
    "What I the Lord have spoken, I have spoken, and I excuse not myself; and though the heavens and the earth pass away, my word shall not pass away, but shall all be fulfilled, whether by mine own voice or by the voice of my servants, it is the same.",
  ],
  [
    "book-of-mormon",
    "2 Nephi",
    2,
    25,
    "Adam fell that men might be; and men are, that they might have joy.",
  ],
  [
    "old-testament",
    "Joshua",
    24,
    15,
    "And if it seem evil unto you to serve the LORD, choose you this day whom ye will serve; whether the gods which your fathers served that were on the other side of the flood, or the gods of the Amorites, in whose land ye dwell: but as for me and my house, we will serve the LORD.",
  ],
  [
    "pearl-of-great-price",
    "Moses",
    1,
    39,
    "For behold, this is my work and my glory—to bring to pass the immortality and eternal life of man.",
  ],
  [
    "book-of-mormon",
    "2 Nephi",
    31,
    20,
    "Wherefore, ye must press forward with a steadfastness in Christ, having a perfect brightness of hope, and a love of God and of all men. Wherefore, if ye shall press forward, feasting upon the word of Christ, and endure to the end, behold, thus saith the Father: Ye shall have eternal life.",
  ],
  [
    "doctrine-and-covenants",
    "D&C",
    4,
    2,
    "Therefore, O ye that embark in the service of God, see that ye serve him with all your heart, might, mind and strength, that ye may stand blameless before God at the last day.",
  ],
  ["old-testament", "Psalms", 23, 1, "The LORD is my shepherd; I shall not want."],
  [
    "book-of-mormon",
    "2 Nephi",
    32,
    3,
    "Angels speak by the power of the Holy Ghost; wherefore, they speak the words of Christ. Wherefore, I said unto you, feast upon the words of Christ; for behold, the words of Christ will tell you all things what ye should do.",
  ],
  [
    "old-testament",
    "Psalms",
    46,
    10,
    "Be still, and know that I am God: I will be exalted among the heathen, I will be exalted in the earth.",
  ],
  ["doctrine-and-covenants", "D&C", 6, 36, "Look unto me in every thought; doubt not, fear not."],
  [
    "book-of-mormon",
    "Mosiah",
    2,
    17,
    "And behold, I tell you these things that ye may learn wisdom; that ye may learn that when ye are in the service of your fellow beings ye are only in the service of your God.",
  ],
  [
    "old-testament",
    "Proverbs",
    3,
    5,
    "Trust in the LORD with all thine heart; and lean not unto thine own understanding.",
  ],
  [
    "pearl-of-great-price",
    "Moses",
    7,
    18,
    "And the Lord called his people ZION, because they were of one heart and one mind, and dwelt in righteousness; and there was no poor among them.",
  ],
  [
    "book-of-mormon",
    "Mosiah",
    3,
    19,
    "For the natural man is an enemy to God, and has been from the fall of Adam, and will be, forever and ever, unless he yields to the enticings of the Holy Spirit, and putteth off the natural man and becometh a saint through the atonement of Christ the Lord, and becometh as a child, submissive, meek, humble, patient, full of love, willing to submit to all things which the Lord seeth fit to inflict upon him, even as a child doth submit to his father.",
  ],
  [
    "doctrine-and-covenants",
    "D&C",
    18,
    10,
    "Remember the worth of souls is great in the sight of God;",
  ],
  [
    "old-testament",
    "Proverbs",
    3,
    6,
    "In all thy ways acknowledge him, and he shall direct thy paths.",
  ],
  [
    "book-of-mormon",
    "Mosiah",
    18,
    9,
    "Yea, and are willing to mourn with those that mourn; yea, and comfort those that stand in need of comfort, and to stand as witnesses of God at all times and in all things, and in all places that ye may be in, even until death, that ye may be redeemed of God, and be numbered with those of the first resurrection, that ye may have eternal life—",
  ],
  [
    "old-testament",
    "Isaiah",
    1,
    18,
    "Come now, and let us reason together, saith the LORD: though your sins be as scarlet, they shall be as white as snow; though they be red like crimson, they shall be as wool.",
  ],
  [
    "doctrine-and-covenants",
    "D&C",
    19,
    23,
    "Learn of me, and listen to my words; walk in the meekness of my Spirit, and you shall have peace in me.",
  ],
  [
    "book-of-mormon",
    "Alma",
    7,
    11,
    "And he shall go forth, suffering pains and afflictions and temptations of every kind; and this that the word might be fulfilled which saith he will take upon him the pains and the sicknesses of his people.",
  ],
  [
    "old-testament",
    "Isaiah",
    40,
    31,
    "But they that wait upon the LORD shall renew their strength; they shall mount up with wings as eagles; they shall run, and not be weary; and they shall walk, and not faint.",
  ],
  [
    "pearl-of-great-price",
    "Abraham",
    3,
    25,
    "And we will prove them herewith, to see if they will do all things whatsoever the Lord their God shall command them;",
  ],
  [
    "book-of-mormon",
    "Alma",
    26,
    12,
    "Yea, I know that I am nothing; as to my strength I am weak; therefore I will not boast of myself, but I will boast of my God, for in his strength I can do all things; yea, behold, many mighty miracles we have wrought in this land, for which we will praise his name forever.",
  ],
  [
    "doctrine-and-covenants",
    "D&C",
    25,
    12,
    "For my soul delighteth in the song of the heart; yea, the song of the righteous is a prayer unto me, and it shall be answered with a blessing upon their heads.",
  ],
  [
    "old-testament",
    "Isaiah",
    41,
    10,
    "Fear thou not; for I am with thee: be not dismayed; for I am thy God: I will strengthen thee; yea, I will help thee; yea, I will uphold thee with the right hand of my righteousness.",
  ],
  [
    "book-of-mormon",
    "Alma",
    32,
    21,
    "And now as I said concerning faith—faith is not to have a perfect knowledge of things; therefore if ye have faith ye hope for things which are not seen, which are true.",
  ],
  [
    "old-testament",
    "Micah",
    6,
    8,
    "He hath shewed thee, O man, what is good; and what doth the LORD require of thee, but to do justly, and to love mercy, and to walk humbly with thy God?",
  ],
  [
    "doctrine-and-covenants",
    "D&C",
    58,
    27,
    "Verily I say, men should be anxiously engaged in a good cause, and do many things of their own free will, and bring to pass much righteousness;",
  ],
  [
    "book-of-mormon",
    "Alma",
    34,
    32,
    "For behold, this life is the time for men to prepare to meet God; yea, behold the day of this life is the day for men to perform their labors.",
  ],
  [
    "new-testament",
    "Matthew",
    5,
    16,
    "Let your light so shine before men, that they may see your good works, and glorify your Father which is in heaven.",
  ],
  [
    "pearl-of-great-price",
    "Joseph Smith—History",
    1,
    17,
    "It no sooner appeared than I found myself delivered from the enemy which held me bound. When the light rested upon me I saw two Personages, whose brightness and glory defy all description, standing above me in the air. One of them spake unto me, calling me by name and said, pointing to the other—This is My Beloved Son. Hear Him!",
  ],
  [
    "book-of-mormon",
    "Alma",
    37,
    6,
    "Now ye may suppose that this is foolishness in me; but behold I say unto you, that by small and simple things are great things brought to pass; and small means in many instances doth confound the wise.",
  ],
  [
    "doctrine-and-covenants",
    "D&C",
    64,
    10,
    "I, the Lord, will forgive whom I will forgive, but of you it is required to forgive all men.",
  ],
  [
    "new-testament",
    "Matthew",
    11,
    28,
    "Come unto me, all ye that labour and are heavy laden, and I will give you rest.",
  ],
  [
    "book-of-mormon",
    "Alma",
    37,
    37,
    "Counsel with the Lord in all thy doings, and he will direct thee for good; yea, when thou liest down at night lie down unto the Lord, that he may watch over you in your sleep; and when thou risest in the morning let thy heart be full of thanks unto God; and if ye do these things, ye shall be lifted up at the last day.",
  ],
  [
    "new-testament",
    "Matthew",
    22,
    37,
    "Jesus said unto him, Thou shalt love the Lord thy God with all thy heart, and with all thy soul, and with all thy mind.",
  ],
  [
    "doctrine-and-covenants",
    "D&C",
    76,
    22,
    "And now, after the many testimonies which have been given of him, this is the testimony, last of all, which we give of him: That he lives!",
  ],
  [
    "book-of-mormon",
    "Helaman",
    5,
    12,
    "And now, my sons, remember, remember that it is upon the rock of our Redeemer, who is Christ, the Son of God, that ye must build your foundation; that when the devil shall send forth his mighty winds, yea, his shafts in the whirlwind, yea, when all his hail and his mighty storm shall beat upon you, it shall have no power over you to drag you down to the gulf of misery and endless wo, because of the rock upon which ye are built, which is a sure foundation, a foundation whereon if men build they cannot fall.",
  ],
  [
    "new-testament",
    "John",
    3,
    16,
    "For God so loved the world, that he gave his only begotten Son, that whosoever believeth in him should not perish, but have everlasting life.",
  ],
  [
    "pearl-of-great-price",
    "Articles of Faith",
    1,
    13,
    "We believe in being honest, true, chaste, benevolent, virtuous, and in doing good to all men; indeed, we may say that we follow the admonition of Paul—We believe all things, we hope all things, we have endured many things, and hope to be able to endure all things. If there is anything virtuous, lovely, or of good report or praiseworthy, we seek after these things.",
  ],
  [
    "book-of-mormon",
    "3 Nephi",
    11,
    11,
    "And behold, I am the light and the life of the world; and I have drunk out of that bitter cup which the Father hath given me, and have glorified the Father in taking upon me the sins of the world, in the which I have suffered the will of the Father in all things from the beginning.",
  ],
  [
    "doctrine-and-covenants",
    "D&C",
    82,
    10,
    "I, the Lord, am bound when ye do what I say; but when ye do not what I say, ye have no promise.",
  ],
  [
    "new-testament",
    "John",
    13,
    34,
    "A new commandment I give unto you, That ye love one another; as I have loved you, that ye also love one another.",
  ],
  [
    "book-of-mormon",
    "3 Nephi",
    18,
    20,
    "And whatsoever ye shall ask the Father in my name, which is right, believing that ye shall receive, behold it shall be given unto you.",
  ],
  [
    "new-testament",
    "John",
    14,
    27,
    "Peace I leave with you, my peace I give unto you: not as the world giveth, give I unto you. Let not your heart be troubled, neither let it be afraid.",
  ],
  [
    "doctrine-and-covenants",
    "D&C",
    88,
    63,
    "Draw near unto me and I will draw near unto you; seek me diligently and ye shall find me; ask, and ye shall receive; knock, and it shall be opened unto you.",
  ],
  [
    "book-of-mormon",
    "Ether",
    12,
    6,
    "And now, I, Moroni, would speak somewhat concerning these things; I would show unto the world that faith is things which are hoped for and not seen; wherefore, dispute not because ye see not, for ye receive no witness until after the trial of your faith.",
  ],
  [
    "new-testament",
    "John",
    16,
    33,
    "These things I have spoken unto you, that in me ye might have peace. In the world ye shall have tribulation: but be of good cheer; I have overcome the world.",
  ],
  [
    "book-of-mormon",
    "Ether",
    12,
    27,
    "And if men come unto me I will show unto them their weakness. I give unto men weakness that they may be humble; and my grace is sufficient for all men that humble themselves before me; for if they humble themselves before me, and have faith in me, then will I make weak things become strong unto them.",
  ],
  [
    "doctrine-and-covenants",
    "D&C",
    88,
    118,
    "And as all have not faith, seek ye diligently and teach one another words of wisdom; yea, seek ye out of the best books words of wisdom; seek learning, even by study and also by faith.",
  ],
  [
    "new-testament",
    "Romans",
    8,
    28,
    "And we know that all things work together for good to them that love God, to them who are the called according to his purpose.",
  ],
  [
    "book-of-mormon",
    "Moroni",
    7,
    45,
    "And charity suffereth long, and is kind, and envieth not, and is not puffed up, seeketh not her own, is not easily provoked, thinketh no evil, and rejoiceth not in iniquity but rejoiceth in the truth, beareth all things, believeth all things, hopeth all things, endureth all things.",
  ],
  [
    "new-testament",
    "Philippians",
    4,
    13,
    "I can do all things through Christ which strengtheneth me.",
  ],
  [
    "doctrine-and-covenants",
    "D&C",
    121,
    7,
    "My son, peace be unto thy soul; thine adversity and thine afflictions shall be but a small moment;",
  ],
  [
    "book-of-mormon",
    "Moroni",
    7,
    47,
    "But charity is the pure love of Christ, and it endureth forever; and whoso is found possessed of it at the last day, it shall be well with him.",
  ],
  [
    "new-testament",
    "2 Timothy",
    1,
    7,
    "For God hath not given us the spirit of fear; but of power, and of love, and of a sound mind.",
  ],
  [
    "book-of-mormon",
    "Moroni",
    10,
    4,
    "And when ye shall receive these things, I would exhort you that ye would ask God, the Eternal Father, in the name of Christ, if these things are not true; and if ye shall ask with a sincere heart, with real intent, having faith in Christ, he will manifest the truth of it unto you, by the power of the Holy Ghost.",
  ],
  [
    "doctrine-and-covenants",
    "D&C",
    121,
    45,
    "Let thy bowels also be full of charity towards all men, and to the household of faith, and let virtue garnish thy thoughts unceasingly; then shall thy confidence wax strong in the presence of God; and the doctrine of the priesthood shall distil upon thy soul as the dews from heaven.",
  ],
  [
    "new-testament",
    "Hebrews",
    11,
    1,
    "Now faith is the substance of things hoped for, the evidence of things not seen.",
  ],
  [
    "book-of-mormon",
    "Moroni",
    10,
    32,
    "Yea, come unto Christ, and be perfected in him, and deny yourselves of all ungodliness; and if ye shall deny yourselves of all ungodliness, and love God with all your might, mind and strength, then is his grace sufficient for you, that by his grace ye may be perfect in Christ; and if by the grace of God ye are perfect in Christ, ye can in nowise deny the power of God.",
  ],
  [
    "new-testament",
    "James",
    1,
    5,
    "If any of you lack wisdom, let him ask of God, that giveth to all men liberally, and upbraideth not; and it shall be given him.",
  ],
  [
    "doctrine-and-covenants",
    "D&C",
    122,
    7,
    "And if thou shouldst be cast into the pit, or into the hands of murderers, and the sentence of death passed upon thee; if thou be cast into the deep; if the billowing surge conspire against thee; if fierce winds become thine enemy; if the heavens gather blackness, and all the elements combine to hedge up the way; and above all, if the very jaws of hell shall gape open the mouth wide after thee, know thou, my son, that all these things shall give thee experience, and shall be for thy good.",
  ],
];
